name: Go
on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        go-versions:
        - "1.19"
        - "1.20"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-versions }}
        cache: false
    - name: Run go test
      run: GO111MODULE=on go test -v -race ./...
